# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
# Trouble Shooting:
# https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#config-file-error

#theme: jekyll-theme-minimal

exclude: ["README.md", "Rakefile", ".rvmrc", ".rbenv-version"]
extensions: [fenced_code_blocks]
excerpt_separator: "<!--more-->"

# Site Company Name, Tagline, Description, and Contact Information.
title: THS
tagline: Tagline.
company:
  name: THS
  site: https://texashighfrequency.com
  description: null
  image: social-image.png
  address_ln1: null
  address_ln2: null
  phone: Phone#
  email: null
  googlemap: null
  # social medias:
  linkedin:   null
  twitter:    null
  facebook:   null
  instagram:  null
  github:     null
  telegram:   null
  discord:    null
  pinterest:  null
  feedburner: null

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url: https://texashighfrequency.com
url: https://texashighfrequency.com
baseurl: ""

# Used when creating press post html pages from markup:
# Press Release posts are located in the _posts directory and are markdown style.
# Read more about formatting here:
# https://heliumjk.github.io/docs/2017/10/08/helium-jekyll-theme-markdown-examples
permalink: /:categories/:year/:month/:day/:title
highlighter: null
markdown: kramdown

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB:
  version: 0.3.0
  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.io)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.io/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.io/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  #https://SecureThisElection.github.io
  BASE_PATH: false

  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #
  analytics:
    provider: google

    google:
      tracking_id: G-4LXSXB9GNS

  #  getclicky:
  #    site_id:

  #  mixpanel:
  #    token: '_MIXPANEL_TOKEN_'

  #  piwik:
  #    baseURL: 'myserver.tld/piwik' # Piwik installation address (without protocol)
  #    idsite: '1'                   # the id of the site on Piwik

  # Settings for sharing helper.
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing:
    provider: false
